// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

module.exports = defineConfig({
  datasource: {
    provider: "postgresql",
    url: process.env.HR_DATABASE_URL,
    schemas: ["prisma/hr/schema.prisma"],
  },
});