// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  datasources: {
    hr: {
      provider: "postgresql",
      url: process.env.HR_DATABASE_URL,
      schemas: ["prisma/hr/schema.prisma"],
    },
    // ... ERP (จะมีหรือไม่ก็ได้)
  },
});